import "./components/Header";
import "./components/Menu";
import "./components/fa-icon";
import "./components/ProjectCard";
import "./components/WorkCard";
import "./components/Terminal";
import "./pages/About"
import "./pages/Projects";
import "./pages/Resume";
